# Generated by Django 5.2.8 on 2025-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bank_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
