# Generated by Django 5.2.8 on 2025-11-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_bank_code_account_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="user",
        ),
    ]
