# Generated by Django 5.2.8 on 2025-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='거래 금액')),
                ('balance', models.IntegerField(verbose_name='거래 후 잔액')),
                ('description', models.CharField(max_length=255, verbose_name='거래 내역')),
                ('is_deposit', models.BooleanField(verbose_name='입출금 타입')),
                ('transaction_type', models.CharField(max_length=255, verbose_name='거래 타입')),
                ('transacted_at', models.DateTimeField(verbose_name='거래 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '계좌 조회',
                'verbose_name_plural': '조회 목록',
                'db_table': 'transaction',
            },
        ),
    ]
