# Generated by Django 5.2.8 on 2025-11-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "입금"),
                            ("WITHDRAW", "출금"),
                            ("TRANSFER", "이체"),
                            ("PAYMENT", "결제"),
                            ("REFUND", "환불"),
                            ("CARD", "카드 결제"),
                            ("OTHER", "기타"),
                            ("ATM", "ATM 거래"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("result_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_deposit", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "거래 내역",
                "verbose_name_plural": "거래 내역 목록",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
