# Generated by Django 5.2.8 on 2025-11-24 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Accounts",
        ),
    ]
