# Generated by Django 5.2.8 on 2025-11-29 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_income', models.BooleanField(verbose_name='분석 대상')),
                ('period', models.CharField(choices=[('DAILY', '일간'), ('WEEKLY', '주간'), ('MONTHLY', '월간'), ('YEARLY', '연간')], max_length=255, verbose_name='분석 기간')),
                ('end_date', models.DateTimeField(verbose_name='분석 종료 날자')),
                ('start_date', models.DateTimeField(verbose_name='분석 시작 날짜')),
                ('description', models.TextField(verbose_name='분석 설명')),
                ('result_image', models.CharField(blank=True, max_length=255, verbose_name='분석 결과')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='계좌')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '분석',
                'verbose_name_plural': '분석 목록',
            },
        ),
    ]
