# Generated by Django 5.2.8 on 2025-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성 여부'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 실행 시각'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True, verbose_name='분석 설명'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='end_date',
            field=models.DateTimeField(verbose_name='분석 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='is_income',
            field=models.BooleanField(verbose_name='수입 여부'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='period',
            field=models.CharField(choices=[('DAILY', '일간'), ('WEEKLY', '주간'), ('MONTHLY', '월간'), ('YEARLY', '연간')], max_length=20, verbose_name='분석 주기'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result_image',
            field=models.CharField(blank=True, max_length=255, verbose_name='분석 결과 이미지'),
        ),
    ]
